Repository exercism/csharp, pull requests merged in 2021-09, with the labels that each got.

#1580 change 'comas' to 'commas'
  concepts/tuples/introduction.md
Labels: x:size/tiny

#1588 Fix prerequisites
  config.json
Labels: x:size/tiny

#1582 Changed method names Nitro() in language and test files. #1581
  exercises/concept/need-for-speed/.meta/Exemplar.cs
  exercises/concept/need-for-speed/NeedForSpeed.cs
  exercises/concept/need-for-speed/NeedForSpeedTests.cs
Labels: x:size/small

#1590 Fixes typo on ifarcher / if_archer
  exercises/concept/annalyns-infiltration/AnnalynsInfiltrationTests.cs
Labels: x:size/tiny

#1595 Add tests for warrior damage
  exercises/concept/wizards-and-warriors/WizardsAndWarriorsTests.cs
Labels: x:size/small

#1611 Fix small grammatical error in introduction
  concepts/do-while-loops/introduction.md
Labels: x:size/tiny

#1628 Fix a number of typos
  exercises/concept/developer-privileges/.docs/hints.md
  exercises/concept/developer-privileges/.docs/instructions.md
  exercises/concept/developer-privileges/.docs/introduction.md
  exercises/concept/developer-privileges/.meta/Exemplar.cs
  exercises/concept/developer-privileges/WhyCantIPushToMain.cs
Labels: x:size/small

#1627 Fix incorrect code sample in instructions
  exercises/concept/instruments-of-texas/.docs/instructions.md
Labels: x:size/tiny

#1626 hyper-optimized-telemetry: improve instructions
  exercises/concept/hyper-optimized-telemetry/.docs/instructions.md
Labels: x:size/small

#1653 remote-control-competition: remove interface stub
  exercises/concept/remote-control-competition/RemoteControlCompetition.cs
Labels: x:size/tiny

#1585 Implement new concept exercise for extension methods
  concepts/extension-methods/.meta/config.json
  concepts/extension-methods/about.md
  concepts/extension-methods/introduction.md
  concepts/extension-methods/links.json
  config.json
  exercises/concept/calculator-conundrum/CalculatorConundrum.cs
  exercises/concept/log-analysis/.docs/hints.md
  exercises/concept/log-analysis/.docs/instructions.md
  exercises/concept/log-analysis/.docs/introduction.md
  exercises/concept/log-analysis/.meta/Exemplar.cs
  exercises/concept/log-analysis/.meta/config.json
  exercises/concept/log-analysis/.meta/design.md
  exercises/concept/log-analysis/LogAnalysis.cs
  exercises/concept/log-analysis/LogAnalysis.csproj
  exercises/concept/log-analysis/LogAnalysisTests.cs
Labels: x:size/large

#1657 1656: Replaced the Eq method in HyperiaForexTests.cs by an inline method
  exercises/concept/hyperia-forex/HyperiaForexTests.cs
Labels: x:size/small

#1661 Fix single letter typo
  exercises/concept/interest-is-interesting/.docs/introduction.md
Labels: x:size/tiny

#1664 [Robot-Name]: Added edge cases in Name
  exercises/practice/robot-name/RobotNameTests.cs
Labels: x:size/medium
